---
title: "Debugging Excercises"
output: 
  html_document: 
    keep_md: yes
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In the following examples, evaluate each problem using the criteria of a minimal reproducible example from [this StackOverflow post](https://stackoverflow.com/help/minimal-reproducible-example). 

Specifically, address the following things: 

1. Are the question and problem description complete?

2. Is the issue reproducible? Does it have a description of the problem, with code that reproduces the problem? What could improve it?

3. Is the example minimal? Does it include extra code or information that is not necessary?

4. Does the question describe any attempted solutions?


Then, using what you know about R and SAS, try to debug the problem using the strategies in [Module 7](https://srvanderplas.github.io/unl-stat850/debugging.html). Once you are thoroughly stumped, or you believe you have solved the problem, compare your solutions to those given on StackOverflow using the link.

# Why Doesn't this R function work?

> I created the following function to append new strings on a vector of strings called "meals". However, when I use this function to append an string input into my "meals" vector, it does not work.

```
 add <- function(str) {
      meals <- append(meals, as.character(str))  
    }
```

[Link](https://stackoverflow.com/questions/39795961/why-doesnt-this-r-function-work?noredirect=1&lq=1) to original SO post. 



# Function not working R

> I've never programmed before and am trying to learn. I'm following that "coursera" course that I've seen other people post about — a course offered by Johns Hopkins on R programming.

> Anyway, this was supposed to be my first function. Yet, it doesn't work! But when I type out all the steps individually, it runs just fine... Can anyone tell me why?

```
pollutantmean <- function(directory, pollutant, id = 1:332){
    x<- list.files("/Users/mike******/Desktop/directory", full.names=TRUE)
    y<- lapply(x, read.csv)
    z<- do.call(rbind.data.frame, y[id])

    mean(z$pollutant, na.rm=TRUE)
}
pollutantmean(specdata,nitrate,1:10)
[1] NA
Warning message:
In mean.default(z$pollutant, na.rm = TRUE) :
  argument is not numeric or logical: returning NA

####

x<- list.files("/Users/mike******/Desktop/specdata",full.names=TRUE)
y<- lapply(x,read.csv)
z<- do.call(rbind.data.frame,y[1:10])
mean(z$nitrate,na.rm=TRUE)
[1] 0.7976266
```


[Link](https://stackoverflow.com/questions/24123224/function-not-working-r/24141502)



# Inexplicable error when trying to export my R notebook

> Getting this error from R Markdown when trying to export my .RMD

```
"Error in filter(Gastropods, Species == "Cellana") :  object 'Species' not found Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> filter"
```

> However, all my plots are coming out successfully. I can clearly see in the data that the species column is there and that Cellana is a species. No spelling errors or anything.

> My first 20 or so lines of code are below


````
`r paste(readLines("debugging_3.txt"), collapse = '\n')`
````

You can find this sample file [here](debugging_3.txt)


[Link](https://stackoverflow.com/questions/44193367/inexplicable-error-when-trying-to-export-my-r-notebook)


# If/Then/Else in SAS Not Working

> Struggling to get this If/Then/Else statement not working. I have two columns: Variable and Value. Variable has the name of the variable and Value has all the potential codes that could be associated with that Variable.

> Example:

```
Variable     Value
Gender         F
Gender         M
```

> I want to create a field called "Flag" and if the value isn't among the list of values, it should flag that field; otherwise, leave that field blank

```
data Want;
length 
Variable $40.
Value $40.
Flag $8.;
set Have (keep = Variable Value);
if (Variable = 'Gender' and Value ^= 'M') then Flag = 'UnkCode'; else Flag="";
if (Variable = 'Gender' and Value ^= 'F') then Flag = 'UnkCode'; else  Flag="";
if (Variable = 'Gender' and Value ^= 'O') then Flag = 'UnkCode'; else Flag="";
if (Variable = 'Gender' and Value ^= 'U') then Flag = 'UnkCode'; else Flag="";
run;
quit;
```

> The dataset I'm using has only has two values for Gender: F and M. For whatever reason, the flag field in both lines has "UnkCode"

> Any idea what I'm doing wrong?


[Link](https://stackoverflow.com/questions/23412048/if-then-else-in-sas-not-working)
