project:
  type: book
  output-dir: docs

book:
  title: "Computing Tools for Statisticians"
  author: "Susan Vanderplas"
  chapters:
    - index.qmd
    - tools.qmd
    - intro-prog.qmd
    - basic-types.qmd
    - data-structures.qmd
    - control-structures.qmd
    - data-programming.qmd
    - references.qmd
  appendices:
    - app-sas.qmd
  favicon: images/favicon.ico
  cover-image: images/cover.png
  site-url: https://srvanderplas.github.io/unl-stat850/
  repo-url: https://github.com/srvanderplas/unl-stat850/
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  number-depth: 3
  toc:
    collapse: section

date: today
date-format: long

bibliography: [references.bib, packages.bib]
biblio-style: apalike


engine: knitr

from: markdown+emoji

format:
  html5:
    css: style.css
    theme: cosmo
    code-link: true
    include-in-header: "header.html"

  # pdf:
  #   documentclass: scrreport
  #epub:
  #  cover-image: cover.png

editor: source

# Knitr options
knitr:
  opts_chunk:
    collapse: true
    message: false
    warning: false
    error: true

execute:
  freeze: auto  # re-render only when source changes
