
```{r setup, echo = F, message = F, warning = F}
library(magrittr)
library(knitr)
library(SASmarkdown)
rmarkdown::html_dependency_font_awesome()
sasexe <- "/usr/local/SASHome/SASFoundation/9.4/bin/sas_u8"
sasopts <- "-ls 75 -noterminal"
knitr::opts_chunk$set(collapse = T, hold = T, cache = T, fig.path = "image/",
                      engine.opts = list(
                        "r" = list(tidy = "styler"), 
                        "sashtmllog" = sasopts, 
                        "saslog" = sasopts,
                        "sas" = sasopts,
                        "sashtml" = sasopts),
                      engine.path = list(
                        sashtmllog = sasexe,
                        saslog = sasexe,
                        sashtml = sasexe,
                        sas = sasexe
                      ),
                      dpi = 300)
```

```{r book-functions, include = F}
.pkgkeeplist <- c("package:stats", "package:graphics", "package:grDevices", "package:utils", "package:datasets", "package:methods", "package:base", "package:SASmarkdown", "package:rmarkdown", "package:knitr", "package:magrittr")

.objkeeplist <- c(".pkgkeeplist", ".objkeeplist", ".reset", "sasexe", "sasopts")

.reset <- function() {
  basic.packages <- .pkgkeeplist

  package.list <- search()[ifelse(unlist(gregexpr("package:", search())) == 1, TRUE, FALSE)]

  package.list <- setdiff(package.list, basic.packages)

  obj.list <- setdiff(ls(), .objkeeplist)

  if (length(package.list) > 0) for (package in package.list) detach(package, character.only = TRUE)
  rm(list = obj.list)
}
```


```{r clear-all-sas-output, include=F, engine='sashtmllog', engine.path = sasexe, engine.opts = sasopts, collectcode = F, echo = F, include = F, results='hide'}
dm log "clear";
dm output "clear";
title1;
footnote1;
ods html close;
ods html; 
```
