--- 
title: "Stat 850: Computing Tools for Statisticians"
author: "Susan Vanderplas"
date: "`r paste('Last Updated: ', Sys.Date())`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Introductions to statistical computing packages and document preparation software. Topics include: graphical techniques, data management, Monte Carlo simulation, dynamic document preparation, presentation software."
---


# Introduction {-}

```{r setup, echo = F}
library(magrittr)
library(knitr)
knitr::opts_chunk$set(collapse = T, cache = T)
```

```{r load-libraries, echo = F, message = F, warning = F, cache = F}

saspath <- "/usr/local/SASHome/SASFoundation/9.4/bin/sas_en"
sasopts <- "-ls 75"
knitr::opts_chunk$set(engine.path=list(sas=saspath, saslog=saspath, sashtml=saspath),
                      engine.opts=list(sas=sasopts, saslog=sasopts, sashtml=sasopts), 
                      comment=NA)
library(SASmarkdown)

```

```{r, include = F}
.pkgkeeplist <- c("package:stats","package:graphics","package:grDevices","package:utils","package:datasets","package:methods","package:base", "package:SASmarkdown", "package:rmarkdown", "package:knitr", "package:magrittr")

.objkeeplist <- c(".pkgkeeplist", ".objkeeplist", ".reset", "saspath", "sasopts")

.reset <- function() {
  basic.packages <- .pkgkeeplist

  package.list <- search()[ifelse(unlist(gregexpr("package:",search()))==1,TRUE,FALSE)]

  package.list <- setdiff(package.list,basic.packages)
  
  obj.list <- setdiff(ls(), .objkeeplist)

  if (length(package.list)>0)  for (package in package.list) detach(package, character.only=TRUE)
  rm(list = obj.list)
}
```
