# .github/workflows/quarto-render.yml
name: Render and deploy Quarto files
on:
  push:
  pull_request:

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    container: rocker/verse:latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_PAT: ${{ secrets.GH_PAT }}
      GITHUB_PAT: ${{ secrets.GH_PAT }}
    steps:
    - uses: actions/checkout@v2

    - name: Install Python dependencies 1
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install -y python3-virtualenv
        sudo apt install -y python3-dev
        sudo apt install -y python3-venv
      shell: /bin/bash {0}

    - name: Set RENV_PATHS_ROOT
      shell: bash
      run: |
        echo "RENV_PATHS_ROOT=${{ runner.temp }}/renv" >> $GITHUB_ENV

    - name: Install and activate renv
      run: |
        pak::pkg_install("rstudio/renv")
        pak::pkg_install("rstudio/fontawesome")
        options(renv.download.override = utils::download.file)
        renv::restore()
      shell: Rscript {0}

    - name: Restore Renv package cache
      uses: actions/cache@v3
      with:
        path: ${{ env.RENV_PATHS_ROOT }}
        key: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{ inputs.cache-version }}-${{ hashFiles('renv.lock') }}
        restore-keys: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{inputs.cache-version }}-


    - name: "Quarto render"
      shell: bash
      run: |
        quarto render --execute-debug

    - name: "Deploy to gh-pages"
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
